[tools]
go = "1.24.0"
java = "corretto-11"
node = "24"
pnpm = "latest"
python = "3.13.3"
terraform = "latest"
uv = "latest"

[settings]
idiomatic_version_file_enable_tools = ["go", "node"]
go_set_gobin = true
